const APP_VERSION = '1.1.1-prototype';
const CACHE_PREFIX='komeri-tools',PRECACHE_NAME=`${CACHE_PREFIX}-precache-v${APP_VERSION}`,DATA_CACHE_NAME=`${CACHE_PREFIX}-data-v${APP_VERSION}`;
const CORE_ASSETS = [
'./','./index.html','./offline.html','./manifest.webmanifest','./version.json','./assets/site.css','./icons/favicon.svg','./icons/icon-192.png','./icons/icon-512.png','./icons/icon-maskable-512.png','./icons/apple-touch-icon.png','./shared/js/pwa-client.js','./shared/js/ean13.js',
'./tools/wood-cut-planner/','./tools/wood-cut-planner/index.html','./tools/wood-cut-planner/styles.css','./tools/wood-cut-planner/js/materials.js','./tools/wood-cut-planner/js/model.js','./tools/wood-cut-planner/js/material-jan.js','./tools/wood-cut-planner/js/jan-camera-ui.js','./tools/wood-cut-planner/js/jan-scanner.js','./tools/wood-cut-planner/js/app.js','./tools/wood-cut-planner/MATERIAL_DATA_FORMAT.md',
'./tools/jan-scanner/','./tools/jan-scanner/index.html','./tools/jan-scanner/styles.css','./tools/jan-scanner/js/app.js','./tools/jan-scanner/js/list-store.js','./tools/jan-scanner/js/scan-consensus.js','./tools/jan-scanner/js/barcode-renderer.js',
'./tools/hose-length/','./tools/hose-length/index.html','./tools/hose-length/styles.css','./tools/hose-length/js/app.js',
'./tools/power-tool-blade-search/','./tools/power-tool-blade-search/index.html','./tools/power-tool-blade-search/styles.css','./tools/power-tool-blade-search/js/app.js','./tools/power-tool-blade-search/js/data.js',
'./tools/chainsaw-parts-search/','./tools/chainsaw-parts-search/index.html','./tools/chainsaw-parts-search/styles.css','./tools/chainsaw-parts-search/js/app.js','./tools/chainsaw-parts-search/js/data.js',
'./tools/pesticide-search/','./tools/pesticide-search/index.html','./tools/pesticide-search/styles.css','./tools/pesticide-search/js/app.js','./tools/pesticide-search/js/multi-crop.js','./tools/pesticide-search/js/multi-crop-ui.js'];
const OPTIONAL_ASSETS = ['./tools/pesticide-search/js/data.js'];
const abs=path=>new URL(path,self.registration.scope).href;
async function put(cache,request,response){if(response?.ok&&response.type==='basic')await cache.put(request,response.clone());return response;}
async function networkFirst(request,cacheName,fallback){const cache=await caches.open(cacheName);try{return await put(cache,request,await fetch(request));}catch{const hit=await cache.match(request,{ignoreSearch:true})||await caches.match(request,{ignoreSearch:true});if(hit)return hit;if(fallback)return caches.match(abs(fallback));throw Error('unavailable');}}
function cacheFirst(request,cacheName,event){const refresh=(async()=>put(await caches.open(cacheName),request,await fetch(request)))();event.waitUntil(refresh.catch(()=>null));return (async()=>await (await caches.open(cacheName)).match(request,{ignoreSearch:true})||await refresh)();}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(PRECACHE_NAME);await cache.addAll(CORE_ASSETS.map(path=>new Request(abs(path),{cache:'reload'})));})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keep=new Set([PRECACHE_NAME,DATA_CACHE_NAME]);await Promise.all((await caches.keys()).filter(name=>name.startsWith(`${CACHE_PREFIX}-`)&&!keep.has(name)).map(name=>caches.delete(name)));await self.clients.claim();})()));
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET'||request.headers.has('range'))return;const url=new URL(request.url);if(url.origin!==location.origin)return;if(request.mode==='navigate'){event.respondWith(networkFirst(request,PRECACHE_NAME,'./offline.html'));return;}if(url.href===abs('./version.json')||url.href===abs('./manifest.webmanifest')){event.respondWith(networkFirst(request,PRECACHE_NAME));return;}const optional=OPTIONAL_ASSETS.some(path=>url.href===abs(path))||/\/js\/data\.js$/.test(url.pathname);event.respondWith(cacheFirst(request,optional?DATA_CACHE_NAME:PRECACHE_NAME,event));});
async function cacheOptional(port){const cache=await caches.open(DATA_CACHE_NAME);for(let i=0;i<OPTIONAL_ASSETS.length;i++){const path=OPTIONAL_ASSETS[i],request=new Request(abs(path),{cache:'reload'}),response=await fetch(request);if(!response.ok)throw Error(`${response.status} ${response.statusText}`);await cache.put(request,response);port?.postMessage({type:'CACHE_PROGRESS',completed:i+1,total:OPTIONAL_ASSETS.length,path});}port?.postMessage({type:'CACHE_COMPLETE',version:APP_VERSION});}
async function optionalStatus(){const cache=await caches.open(DATA_CACHE_NAME),states=await Promise.all(OPTIONAL_ASSETS.map(path=>cache.match(abs(path),{ignoreSearch:true})));return{complete:states.every(Boolean),cached:states.filter(Boolean).length,total:states.length,version:APP_VERSION};}
self.addEventListener('message',event=>{const message=event.data||{},port=event.ports?.[0];if(message.type==='SKIP_WAITING'){self.skipWaiting();return;}if(message.type==='GET_VERSION'){port?.postMessage({type:'VERSION',version:APP_VERSION});return;}if(message.type==='CHECK_OPTIONAL_CACHE'){event.waitUntil(optionalStatus().then(status=>port?.postMessage({type:'OPTIONAL_CACHE_STATUS',...status})).catch(error=>port?.postMessage({type:'ERROR',message:error.message})));return;}if(message.type==='CACHE_OPTIONAL')event.waitUntil(cacheOptional(port).catch(error=>port?.postMessage({type:'ERROR',message:error.message})));});
