importScripts('./sw-assets.js');
const APP_VERSION='1.2.0-prototype';
const CACHE_PREFIX='komeri-tools';
const PRECACHE_NAME=`${CACHE_PREFIX}-precache-v${APP_VERSION}`;
const DATA_CACHE_NAME=`${CACHE_PREFIX}-data-v${APP_VERSION}`;
const CORE_ASSETS=['./','./index.html','./offline.html','./manifest.webmanifest','./version.json','./sw-assets.js','./assets/site.css','./assets/site.js','./icons/favicon.svg','./icons/icon-192.png','./icons/icon-512.png','./shared/js/jan-code.js','./shared/js/pwa-client.js','./tools/wood-cut-planner/','./tools/wood-cut-planner/index.html','./tools/wood-cut-planner/styles.css','./tools/wood-cut-planner/js/materials.js','./tools/wood-cut-planner/js/model.js','./tools/wood-cut-planner/js/material-jan.js','./tools/wood-cut-planner/js/jan-camera-ui.js','./tools/wood-cut-planner/js/jan-scanner.js','./tools/wood-cut-planner/js/app.js','./tools/wood-cut-planner/js/session-storage.js','./tools/wood-cut-planner/js/session-ui.js','./tools/wood-cut-planner/js/session-tabs-basic.js','./tools/wood-cut-planner/js/session-auto-add.js',...self.KOMERI_EXTRA_CORE_ASSETS];
const OPTIONAL_ASSETS=['./tools/pesticide-search/js/all-data-extra.js'];
const absoluteUrl=path=>new URL(path,self.registration.scope).href;
self.addEventListener('install',event=>event.waitUntil(caches.open(PRECACHE_NAME).then(cache=>cache.addAll(CORE_ASSETS.map(path=>new Request(absoluteUrl(path),{cache:'reload'}))))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(names=>Promise.all(names.filter(name=>name.startsWith(`${CACHE_PREFIX}-`)&&!new Set([PRECACHE_NAME,DATA_CACHE_NAME]).has(name)).map(name=>caches.delete(name)))).then(()=>self.clients.claim())));
async function cacheFirst(request,cacheName){const cache=await caches.open(cacheName);const found=await cache.match(request,{ignoreSearch:true})||await caches.match(request,{ignoreSearch:true});if(found)return found;const response=await fetch(request);if(response.ok&&response.type==='basic')await cache.put(request,response.clone());return response;}
async function networkFirst(request,fallback){try{const response=await fetch(request);const cache=await caches.open(PRECACHE_NAME);if(response.ok&&response.type==='basic')await cache.put(request,response.clone());return response;}catch{return await caches.match(request,{ignoreSearch:true})||caches.match(absoluteUrl(fallback));}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==location.origin)return;if(request.mode==='navigate')return event.respondWith(networkFirst(request,'./offline.html'));const optional=OPTIONAL_ASSETS.some(path=>url.href===absoluteUrl(path));event.respondWith(cacheFirst(request,optional?DATA_CACHE_NAME:PRECACHE_NAME));});
async function optionalStatus(){const cache=await caches.open(DATA_CACHE_NAME);const states=await Promise.all(OPTIONAL_ASSETS.map(path=>cache.match(absoluteUrl(path)).then(Boolean)));return{complete:states.every(Boolean),cached:states.filter(Boolean).length,total:states.length,version:APP_VERSION};}
async function cacheOptional(port){const cache=await caches.open(DATA_CACHE_NAME);for(let index=0;index<OPTIONAL_ASSETS.length;index+=1){const path=OPTIONAL_ASSETS[index];const response=await fetch(new Request(absoluteUrl(path),{cache:'reload'}));if(!response.ok)throw new Error(String(response.status));await cache.put(absoluteUrl(path),response);port?.postMessage({type:'CACHE_PROGRESS',completed:index+1,total:OPTIONAL_ASSETS.length,path});}port?.postMessage({type:'CACHE_COMPLETE',version:APP_VERSION});}
self.addEventListener('message',event=>{const message=event.data||{};const port=event.ports?.[0];if(message.type==='SKIP_WAITING')return self.skipWaiting();if(message.type==='GET_VERSION')return port?.postMessage({type:'VERSION',version:APP_VERSION});if(message.type==='CHECK_OPTIONAL_CACHE')return event.waitUntil(optionalStatus().then(value=>port?.postMessage({type:'OPTIONAL_CACHE_STATUS',...value})));if(message.type==='CACHE_OPTIONAL')event.waitUntil(cacheOptional(port).catch(error=>port?.postMessage({type:'ERROR',message:error.message})));});
